version: '3.3'

services:
  web:
    build: ./app
#    command: cd /django-code/crud-docker-compose/stocks_products && gunicorn stocks_products.wsgi -b 0.0.0.0:8000
#    volumes:
#      - ./app/:/django-code
#    ports:
#      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=netol_user
      - POSTGRES_PASSWORD=netol_password
      - POSTGRES_DB=netol_db
#    ports: 
#      - 5432:5432
  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  postgres_data:

